name: debian-fish-bookworm docker container image creation
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 18 * * *'
jobs:
  push_to_registry:
    name: Build docker image from Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Set container image name and tag
        run: |
          echo "image-name=debian-fish" >> $GITHUB_OUTPUT
          echo "tag=bookworm" >> $GITHUB_OUTPUT
        id: container
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          context: ./docker_arm64
          tags: ghcr.io/${{ github.repository_owner }}/${{ steps.container.outputs.image-name }}:${{ steps.container.outputs.tag }}
